CREATE TABLE `mydb`.`task` (
    `NRTAREFA` INT NOT NULL,
    `NMTAREFA` VARCHAR(255) NULL,
    `ESTADOTAREFA` VARCHAR(255) NULL,
    `FOTOTAREFA` VARCHAR(45) NULL,
    PRIMARY KEY (`NRTAREFA`)
 );

 ALTER TABLE `mydb`.`task`
 CHANGE COLUMN `NRTAREFA` `NRTAREFA` INT(11) NOT NULL AUTO_INCREMENT ,
 ADD UNIQUE INDEX `id_UNIQUE` (`NRTAREFA` ASC);